# Cấu hình đè khi ứng dụng chạy trong Container Docker (profile: docker)
spring:
  datasource:
    # URL trỏ tới host là "db" (tên service trong docker-compose.yml thay vì localhost)
    url: jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:inventory_db}
    username: ${DB_USER:thanvinh}
    password: ${DB_PASS:NamMoi2020}

  rabbitmq:
    # Host trỏ tới "rabbitmq" thay cho localhost
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672

  data:
    redis:
      # Host trỏ tới "redis"
      host: ${REDIS_HOST:redis}
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Tắt log SQL để giảm tải rác log khi chạy trên server Docker
